name: Buddy-Benchmark CI

on:
  push:
    branches: ['**']       # or whatever branch should trigger the run
  pull_request:

jobs:
  bench:
    runs-on: self-hosted    # your own actions-runner machine
    permissions:
      contents: read
      pages: write
      id-token: write       # required by Pages deploy

    steps:
    # ------------------------------------------------------------
    # 1) check out the two source trees side-by-side
    # ------------------------------------------------------------
    - name: Update local clones
      run: |
        set -e
        cd /home/quliu/buddy-complier-workspace/buddy-benchmark
        git pull --ff-only

    # ------------------------------------------------------------
    # 2) run everything in the Docker sandbox
    # ------------------------------------------------------------
    - name: Build & run benchmarks
      run: |
        cd /home/quliu/buddy-complier-workspace/
        chmod +x /home/quliu/buddy-complier-workspace/buddy-benchmark/scripts/run_docker.sh
        /home/quliu/buddy-complier-workspace/buddy-benchmark/scripts/run_docker.sh


    # after the script we have ./test_result in the workspace ---------

    # ------------------------------------------------------------
    # 3) keep a raw download for debugging
    # ------------------------------------------------------------
    - name: Upload raw logs as artifact
      uses: actions/upload-artifact@v4
      with:
        name: vectorization-logs-${{ github.sha }}
        path: buddy-benchmark/test_result
        retention-days: 30

    # ------------------------------------------------------------
    # 4) convert *.log → HTML
    # ------------------------------------------------------------
    - name: Build mini-site
      working-directory: buddy-benchmark
      run: |
        python scripts/logs2html.py test_result site

    # ------------------------------------------------------------
    # 5) publish the site to GitHub Pages
    # ------------------------------------------------------------
    - name: Upload site artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: buddy-benchmark/site

    - name: Deploy to Pages
      id: deploy
      uses: actions/deploy-pages@v4

    outputs:
      page_url: ${{ steps.deploy.outputs.page_url }}
